assignments:
  - subject: 'BCSH2'
    name: 'Los_zadanos'
    deadline: '2024-03-02T00:00'
    checkIntervalCron: '* * * * * *'
    sourceRepositoryUrl: 'https://gitserver.com/assignment/BCSH2/exercise-01/'
    configPath: 'master/jenkins/config/defaultConfig.xml'
    jenkinsfilePath: 'master/jenkins/jenkinsfile/Maven.Jenkinsfile'
  - subject: 'BCSH3'
    name: 'BP_CI_Maven_HD'
    deadline: '2024-03-02T00:00'
    checkIntervalCron: '*/5 * * * * *'
    sourceRepositoryUrl: 'https://github.com/Majkle/BP_CI_Maven_Source.git'
    configPath: 'master/jenkins/config/defaultConfig.xml'
    jenkinsfilePath: 'master/jenkins/jenkinsfile/Maven.Jenkinsfile'
  - subject: 'BCSH3'
    name: 'BP_CI_Maven_NHD'
    sourceRepositoryUrl: 'https://github.com/Majkle/BP_CI_Maven_Source.git'
    configPath: 'master/jenkins/config/defaultConfig.xml'
    jenkinsfilePath: 'master/jenkins/jenkinsfile/Maven.Jenkinsfile'
  - subject: 'BCSH3'
    name: 'exercise-03'
    sourceRepositoryUrl: 'https://github.com/Majkle/BP_CI_Maven_Source.git'
    configPath: 'master/jenkins/config/defaultConfig.xml'
    jenkinsfilePath: 'master/jenkins/jenkinsfile/Maven.Jenkinsfile'
  - subject: 'BCSH3'
    name: 'exercise-04'
    sourceRepositoryUrl: 'https://github.com/Majkle/BP_CI_Maven_Source.git'
    configPath: 'master/jenkins/config/defaultConfig.xml'
    jenkinsfilePath: 'master/jenkins/jenkinsfile/Maven.Jenkinsfile'
  - subject: 'BCSH3'
    name: 'exercise-05'
    sourceRepositoryUrl: 'https://github.com/Majkle/BP_CI_Maven_Source.git'
    configPath: 'master/jenkins/config/defaultConfig.xml'
    jenkinsfilePath: 'master/jenkins/jenkinsfile/Maven.Jenkinsfile'
  - subject: 'BCSH3'
    name: 'exercise-06'
    sourceRepositoryUrl: 'https://github.com/Majkle/BP_CI_Maven_Source.git'
    configPath: 'master/jenkins/config/defaultConfig.xml'
    jenkinsfilePath: 'master/jenkins/jenkinsfile/Maven.Jenkinsfile'
  - subject: 'BCSH3'
    name: 'exercise-07'
    sourceRepositoryUrl: 'https://github.com/Majkle/BP_CI_Maven_Source.git'
    configPath: 'master/jenkins/config/defaultConfig.xml'
    jenkinsfilePath: 'master/jenkins/jenkinsfile/Maven.Jenkinsfile'
  - subject: 'BCSH3'
    name: 'exercise-08'
    sourceRepositoryUrl: 'https://github.com/Majkle/BP_CI_Maven_Source.git'
    configPath: 'master/jenkins/config/defaultConfig.xml'
    jenkinsfilePath: 'master/jenkins/jenkinsfile/Maven.Jenkinsfile'
  - subject: 'BCSH3'
    name: 'exercise-09'
    sourceRepositoryUrl: 'https://github.com/Majkle/BP_CI_Maven_Source.git'
    configPath: 'master/jenkins/config/defaultConfig.xml'
    jenkinsfilePath: 'master/jenkins/jenkinsfile/Maven.Jenkinsfile'
  - subject: 'BCSH3'
    name: 'exercise-10'
    sourceRepositoryUrl: 'https://github.com/Majkle/BP_CI_Maven_Source.git'
    configPath: 'master/jenkins/config/defaultConfig.xml'
    jenkinsfilePath: 'master/jenkins/jenkinsfile/Maven.Jenkinsfile'
  - subject: 'BCSH3'
    name: 'exercise-11'
    sourceRepositoryUrl: 'https://github.com/Majkle/BP_CI_Maven_Source.git'
    configPath: 'master/jenkins/config/defaultConfig.xml'
    jenkinsfilePath: 'master/jenkins/jenkinsfile/Maven.Jenkinsfile'
  - subject: 'BCSH3'
    name: 'exercise-12'
    sourceRepositoryUrl: 'https://github.com/Majkle/BP_CI_Maven_Source.git'
    configPath: 'master/jenkins/config/defaultConfig.xml'
    jenkinsfilePath: 'master/jenkins/jenkinsfile/Maven.Jenkinsfile'
  - subject: 'BCSH3'
    name: 'exercise-13'
    sourceRepositoryUrl: 'https://github.com/Majkle/BP_CI_Maven_Source.git'
    configPath: 'master/jenkins/config/defaultConfig.xml'
    jenkinsfilePath: 'master/jenkins/jenkinsfile/Maven.Jenkinsfile'
  - subject: 'BCSH3'
    name: 'exercise-14'
    sourceRepositoryUrl: 'https://github.com/Majkle/BP_CI_Maven_Source.git'
    configPath: 'master/jenkins/config/defaultConfig.xml'
    jenkinsfilePath: 'master/jenkins/jenkinsfile/Maven.Jenkinsfile'
  - subject: 'BCSH3'
    name: 'exercise-15'
    sourceRepositoryUrl: 'https://github.com/Majkle/BP_CI_Maven_Source.git'
    configPath: 'master/jenkins/config/defaultConfig.xml'
    jenkinsfilePath: 'master/jenkins/jenkinsfile/Maven.Jenkinsfile'
  - subject: 'BCSH3'
    name: 'exercise-16'
    sourceRepositoryUrl: 'https://github.com/Majkle/BP_CI_Maven_Source.git'
    configPath: 'master/jenkins/config/defaultConfig.xml'
    jenkinsfilePath: 'master/jenkins/jenkinsfile/Maven.Jenkinsfile'
  - subject: 'BCSH3'
    name: 'exercise-17'
    sourceRepositoryUrl: 'https://github.com/Majkle/BP_CI_Maven_Source.git'
    configPath: 'master/jenkins/config/defaultConfig.xml'
    jenkinsfilePath: 'master/jenkins/jenkinsfile/Maven.Jenkinsfile'
  - subject: 'BCSH3'
    name: 'exercise-18'
    sourceRepositoryUrl: 'https://github.com/Majkle/BP_CI_Maven_Source.git'
    configPath: 'master/jenkins/config/defaultConfig.xml'
    jenkinsfilePath: 'master/jenkins/jenkinsfile/Maven.Jenkinsfile'
  - subject: 'BCSH3'
    name: 'exercise-19'
    sourceRepositoryUrl: 'https://github.com/Majkle/BP_CI_Maven_Source.git'
    configPath: 'master/jenkins/config/defaultConfig.xml'
    jenkinsfilePath: 'master/jenkins/jenkinsfile/Maven.Jenkinsfile'
  - subject: 'BCSH3'
    name: 'exercise-20'
    sourceRepositoryUrl: 'https://github.com/Majkle/BP_CI_Maven_Source.git'
    configPath: 'master/jenkins/config/defaultConfig.xml'
    jenkinsfilePath: 'master/jenkins/jenkinsfile/Maven.Jenkinsfile'
  - subject: 'BCSH3'
    name: 'exercise-21'
    sourceRepositoryUrl: 'https://github.com/Majkle/BP_CI_Maven_Source.git'
    configPath: 'master/jenkins/config/defaultConfig.xml'
    jenkinsfilePath: 'master/jenkins/jenkinsfile/Maven.Jenkinsfile'
  - subject: 'BCSH3'
    name: 'exercise-22'
    sourceRepositoryUrl: 'https://github.com/Majkle/BP_CI_Maven_Source.git'
    configPath: 'master/jenkins/config/defaultConfig.xml'
    jenkinsfilePath: 'master/jenkins/jenkinsfile/Maven.Jenkinsfile'
  - subject: 'BCSH3'
    name: 'exercise-23'
    sourceRepositoryUrl: 'https://github.com/Majkle/BP_CI_Maven_Source.git'
    configPath: 'master/jenkins/config/defaultConfig.xml'
    jenkinsfilePath: 'master/jenkins/jenkinsfile/Maven.Jenkinsfile'
  - subject: 'BCSH3'
    name: 'exercise-24'
    sourceRepositoryUrl: 'https://github.com/Majkle/BP_CI_Maven_Source.git'
    configPath: 'master/jenkins/config/defaultConfig.xml'
    jenkinsfilePath: 'master/jenkins/jenkinsfile/Maven.Jenkinsfile'
  - subject: 'BCSH3'
    name: 'exercise-25'
    sourceRepositoryUrl: 'https://github.com/Majkle/BP_CI_Maven_Source.git'
    configPath: 'master/jenkins/config/defaultConfig.xml'
    jenkinsfilePath: 'master/jenkins/jenkinsfile/Maven.Jenkinsfile'
subjects:
  - abbreviation: 'BCSH3'
    repositoryUrlTemplate: 'https://github.com/%STUDENT-GIT-ID%/%ASSIGNMENT-NAME%.git'
    students:
      - stId: 'st12345'
        name: 'Pepa Von Depa'
        gitId: 'pepikVonDepik'
        groups:
          - 'st16'
          - 'ut15'
      - stId: 'st54321'
        name: 'Patrik Uhlir'
        gitId: 'pata'
        groups:
          - 'st16'
          - 'ut10'
      - stId: 'st66666'
        name: 'Pepa Franta'
        gitId: 'pefa'
        groups: 'st16'
      - stId: 'st67089'
        name: 'aaaaa bbbb'
        gitId: 'Majkle'
        groups: 'st16'
      - stId: 'st67059'
        name: 'aaaaa bbbb'
        gitId: 'Majkle'
        groups: 'st16'
      - stId: 'st67489'
        name: 'aaaaa bbbb'
        gitId: 'Majkle'
        groups: 'ut10'
      - stId: 'st67029'
        name: 'aaaaa bbbb'
        gitId: 'Majkle'
        groups: 'po15'
      - stId: 'st677089'
        name: 'aaaaa bbbb'
        gitId: 'Majkle'
        groups: 'ut10'
      - stId: 'st7089'
        name: 'aaaaa bbbb'
        gitId: 'Majkle'
        groups: 'po15'
      - stId: 'st670889'
        name: 'aaaaa bbbb'
        gitId: 'Majkle'
        groups: 'ut10'
  - abbreviation: 'BCSH2'
    repositoryUrlTemplate: 'https://github.com/%STUDENT-GIT-ID%/%ASSIGNMENT-NAME%.git'
    students:
      - stId: 'st12345'
        name: 'Pepa Von Depa'
        gitId: 'notPepikVonDepik'
        groups:
          - 'ut15'
      - stId: 'st000'
        name: 'Nob ody'
        gitId: 'nobody'
        groups: 'st16'
      - stId: 'st67089'
        name: 'aaaaa bbbb'
        gitId: 'Majkle'
        groups: 'st16'
  - abbreviation: 'SEM_A'
    repositoryUrlTemplate: 'https://github.com/%STUDENT-GIT-ID%/%ASSIGNMENT-NAME%.git'
    students:
      - stId: 'st5555555555'
        name: 'Pepa Von Depa'
        gitId: 'Majkle'
        groups: 'po08'
  - abbreviation: 'SEM_B'
    repositoryUrlTemplate: 'https://github.com/%STUDENT-GIT-ID%/%ASSIGNMENT-NAME%.git'
    students:
      - stId: 'st6666'
        name: 'Pepa Von Depa'
        gitId: 'Majkle'
        groups: 'ut10'
  - abbreviation: 'SEM_C'
    repositoryUrlTemplate: 'https://github.com/%STUDENT-GIT-ID%/%ASSIGNMENT-NAME%.git'
    students:
      - stId: 'st77777'
        name: 'Pepa Z Depa'
        gitId: 'Majkle'
        groups: 'st16'